version: "2"

services:
  backend:
    build: .
    ports:
      - 8000:8000
      - 9229:9229 # debugger port
    volumes:
      - .:/usr/src/app #it maps all in this directory to docker directory (defined in Dockerfile) to avoid repetitve processes (rm container, build, ...) for any change
      - /usr/src/app/node_modules #volume for node_modules only
    command: yarn start:docker
    environment:
      PORT: 8000
